# Generated by Django 4.2.6 on 2024-01-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="pdf_books/",
            ),
        ),
    ]
